//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Level/LDtk/Proto.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tulip.Editor.LDtk
{
    /// <summary>
    /// LDtk Enum for LDtk_Enums.g
    /// </summary>
    public enum Collider_Type
    {
        Grid
    }
}